export const PRODUCT_NAME = 'BarberEX'
export const PRODUCT_MONOGRAM = 'BX'
export const PRODUCT_TAGLINE = 'Expertise operacional, agenda inteligente e gestao premium para barbearias.'
export const PRODUCT_POSITIONING = 'Expertise, experiencia premium e execucao inteligente para a operacao real da barbearia.'
export const PRODUCT_LOADING_LABEL = 'Carregando sua operacao com precisao'
