import {
  AppointmentBillingModel,
  AppointmentSource,
  AppointmentStatus,
  CategoryType,
  CustomerType,
  PaymentMethod,
  SubscriptionStatus,
  UserRole,
} from '@prisma/client'
import type {
  ScheduleBlueprint,
  SeedBarbershopDefinition,
  SeedCampaignMetricDefinition,
  SeedCategoryDefinition,
  SeedCustomerDefinition,
  SeedExpenseTemplate,
  SeedProfessionalDefinition,
  SeedServiceDefinition,
  SeedSupplyDefinition,
  SeedUserDefinition,
} from './types'

export const DEMO_PASSWORD = 'demo123456'
export const HISTORY_MONTHS = 6

export const DEMO_BARBERSHOP: SeedBarbershopDefinition = {
  name: 'Barbearia Linha Nobre',
  slug: 'linha-nobre',
  address: 'Rua Augusta, 1450 - Consolacao, Sao Paulo',
  phone: '(11) 99888-4400',
  email: 'contato@linhanobre.com.br',
  timezone: 'America/Sao_Paulo',
  onboardingStep: 4,
}

export const DEMO_USERS: SeedUserDefinition[] = [
  { key: 'owner', name: 'Bruno Almeida', email: 'gestao@linhanobre.com.br', role: UserRole.OWNER },
  { key: 'manager', name: 'Camila Torres', email: 'gerencia@linhanobre.com.br', role: UserRole.MANAGER },
  { key: 'financial', name: 'Juliana Martins', email: 'financeiro@linhanobre.com.br', role: UserRole.FINANCIAL },
  { key: 'lucas-ribeiro', name: 'Lucas Ribeiro', email: 'lucas@linhanobre.com.br', role: UserRole.BARBER },
  { key: 'rafael-costa', name: 'Rafael Costa', email: 'rafael@linhanobre.com.br', role: UserRole.BARBER },
  { key: 'matheus-lima', name: 'Matheus Lima', email: 'matheus@linhanobre.com.br', role: UserRole.BARBER },
]

export const PROFESSIONAL_DEFINITIONS: SeedProfessionalDefinition[] = [
  {
    key: 'lucas-ribeiro',
    name: 'Lucas Ribeiro',
    email: 'lucas@linhanobre.com.br',
    phone: '(11) 99111-2201',
    commissionRate: 42,
    haircutPrice: 62,
    beardPrice: 47,
    comboPrice: 96,
    acceptsWalkIn: true,
    acceptsSubscription: true,
    baseAppointments: 11,
    ticketBoost: 3,
    rotation: ['corte-barba-premium', 'degrade-signature', 'corte-classic', 'pigmentacao-natural'],
  },
  {
    key: 'rafael-costa',
    name: 'Rafael Costa',
    email: 'rafael@linhanobre.com.br',
    phone: '(11) 99222-3302',
    commissionRate: 40,
    haircutPrice: 58,
    beardPrice: 44,
    comboPrice: 90,
    acceptsWalkIn: true,
    acceptsSubscription: true,
    baseAppointments: 9,
    ticketBoost: 2,
    rotation: ['corte-classic', 'corte-barba-premium', 'barba-terapia', 'hidratacao-capilar'],
  },
  {
    key: 'matheus-lima',
    name: 'Matheus Lima',
    email: 'matheus@linhanobre.com.br',
    phone: '(11) 99333-4403',
    commissionRate: 36,
    haircutPrice: 54,
    beardPrice: 39,
    comboPrice: 82,
    acceptsWalkIn: true,
    acceptsSubscription: false,
    baseAppointments: 8,
    ticketBoost: 0,
    rotation: ['corte-classic', 'barba-terapia', 'degrade-signature', 'hidratacao-capilar'],
  },
]

export const CATEGORY_DEFINITIONS: SeedCategoryDefinition[] = [
  { key: 'servicos', name: 'Servicos', type: CategoryType.REVENUE, color: '#7c3aed' },
  { key: 'assinaturas', name: 'Assinaturas', type: CategoryType.REVENUE, color: '#8b5cf6' },
  { key: 'produtos', name: 'Produtos', type: CategoryType.REVENUE, color: '#06b6d4' },
  { key: 'combo-premium', name: 'Combo Premium', type: CategoryType.REVENUE, color: '#f59e0b' },
  { key: 'aluguel', name: 'Aluguel', type: CategoryType.EXPENSE_FIXED, color: '#f97316' },
  { key: 'folha', name: 'Folha e pro-labore', type: CategoryType.EXPENSE_FIXED, color: '#dc2626' },
  { key: 'utilidades', name: 'Energia e agua', type: CategoryType.EXPENSE_FIXED, color: '#eab308' },
  { key: 'software', name: 'Internet e software', type: CategoryType.EXPENSE_FIXED, color: '#38bdf8' },
  { key: 'insumos', name: 'Insumos', type: CategoryType.EXPENSE_VARIABLE, color: '#a855f7' },
  { key: 'marketing', name: 'Marketing local', type: CategoryType.EXPENSE_VARIABLE, color: '#ec4899' },
  { key: 'manutencao', name: 'Manutencao', type: CategoryType.EXPENSE_VARIABLE, color: '#64748b' },
]

export const SUPPLY_DEFINITIONS: SeedSupplyDefinition[] = [
  { key: 'pomada', name: 'Pomada Modeladora Premium', unit: 'un', unitCost: 18.0 },
  { key: 'oleo-barba', name: 'Oleo de Barba', unit: 'ml', unitCost: 0.19 },
  { key: 'shampoo', name: 'Shampoo Premium', unit: 'ml', unitCost: 0.07 },
  { key: 'lamina', name: 'Lamina Descartavel', unit: 'un', unitCost: 1.4 },
  { key: 'pigmento', name: 'Pigmento Natural', unit: 'g', unitCost: 0.35 },
  { key: 'oxidante', name: 'Oxidante Suave', unit: 'ml', unitCost: 0.05 },
  { key: 'mascara', name: 'Mascara Capilar', unit: 'ml', unitCost: 0.18 },
  { key: 'toalha', name: 'Toalha Premium', unit: 'un', unitCost: 0.9 },
]

export const SERVICE_DEFINITIONS: SeedServiceDefinition[] = [
  {
    key: 'corte-classic',
    name: 'Corte Classic',
    description: 'O corte mais pedido da casa, com boa margem e giro rapido.',
    price: 55,
    duration: 35,
    priceCategory: 'HAIRCUT',
    pricing: { cardFeePercent: 3.2, taxPercent: 0, commissionPercent: 38, directCost: 2.5, suggestedPrice: 58 },
    inputs: [
      { supplyKey: 'shampoo', quantity: 8 },
      { supplyKey: 'pomada', quantity: 0.12 },
      { supplyKey: 'toalha', quantity: 1 },
    ],
  },
  {
    key: 'corte-barba-premium',
    name: 'Corte + Barba Premium',
    description: 'Combo de maior ticket para aumentar faturamento sem lotar agenda.',
    price: 88,
    duration: 60,
    priceCategory: 'COMBO',
    pricing: { cardFeePercent: 3.2, taxPercent: 0, commissionPercent: 40, directCost: 4.5, suggestedPrice: 92 },
    inputs: [
      { supplyKey: 'shampoo', quantity: 10 },
      { supplyKey: 'oleo-barba', quantity: 4 },
      { supplyKey: 'lamina', quantity: 1 },
      { supplyKey: 'pomada', quantity: 0.18 },
      { supplyKey: 'toalha', quantity: 1 },
    ],
  },
  {
    key: 'barba-terapia',
    name: 'Barba Terapia',
    description: 'Servico de alta recorrencia que ajuda a sustentar o ticket medio.',
    price: 42,
    duration: 25,
    priceCategory: 'BEARD',
    pricing: { cardFeePercent: 3.2, taxPercent: 0, commissionPercent: 36, directCost: 1.5, suggestedPrice: 45 },
    inputs: [
      { supplyKey: 'oleo-barba', quantity: 5 },
      { supplyKey: 'lamina', quantity: 1 },
      { supplyKey: 'toalha', quantity: 1 },
    ],
  },
  {
    key: 'degrade-signature',
    name: 'Degrade Signature',
    description: 'Servico premium para clientes recorrentes e agenda valorizada.',
    price: 65,
    duration: 45,
    priceCategory: 'HAIRCUT',
    pricing: { cardFeePercent: 3.2, taxPercent: 0, commissionPercent: 39, directCost: 3, suggestedPrice: 69 },
    inputs: [
      { supplyKey: 'shampoo', quantity: 9 },
      { supplyKey: 'pomada', quantity: 0.15 },
      { supplyKey: 'toalha', quantity: 1 },
    ],
  },
  {
    key: 'pigmentacao-natural',
    name: 'Pigmentacao Natural',
    description: 'Servico de alto valor para puxar ticket e mostrar versatilidade.',
    price: 95,
    duration: 55,
    priceCategory: 'OTHER',
    pricing: { cardFeePercent: 3.2, taxPercent: 0, commissionPercent: 42, directCost: 6, suggestedPrice: 104 },
    inputs: [
      { supplyKey: 'shampoo', quantity: 6 },
      { supplyKey: 'pigmento', quantity: 12 },
      { supplyKey: 'oxidante', quantity: 25 },
      { supplyKey: 'toalha', quantity: 1 },
    ],
  },
  {
    key: 'hidratacao-capilar',
    name: 'Hidratacao Capilar',
    description: 'Upsell simples para elevar margem nos dias de maior fluxo.',
    price: 48,
    duration: 30,
    priceCategory: 'OTHER',
    pricing: { cardFeePercent: 3.2, taxPercent: 0, commissionPercent: 37, directCost: 3.2, suggestedPrice: 52 },
    inputs: [
      { supplyKey: 'mascara', quantity: 20 },
      { supplyKey: 'shampoo', quantity: 6 },
      { supplyKey: 'toalha', quantity: 1 },
    ],
  },
]

export const CUSTOMER_DEFINITIONS: SeedCustomerDefinition[] = [
  {
    key: 'carlos-mendes',
    name: 'Carlos Mendes',
    phone: '(11) 99123-1101',
    email: 'carlos.mendes@email.com',
    type: CustomerType.SUBSCRIPTION,
    subscriptionPrice: 199.9,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    preferredProfessionalKey: 'lucas-ribeiro',
    notes: 'Cliente assinatura com alto indice de retorno.',
  },
  {
    key: 'pedro-salles',
    name: 'Pedro Salles',
    phone: '(11) 99123-1102',
    email: 'pedro.salles@email.com',
    type: CustomerType.SUBSCRIPTION,
    subscriptionPrice: 199.9,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    preferredProfessionalKey: 'rafael-costa',
    notes: 'Gosta de combo premium e costuma marcar pelo WhatsApp.',
  },
  {
    key: 'thiago-rocha',
    name: 'Thiago Rocha',
    phone: '(11) 99123-1103',
    email: 'thiago.rocha@email.com',
    type: CustomerType.SUBSCRIPTION,
    subscriptionPrice: 199.9,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    preferredProfessionalKey: 'rafael-costa',
  },
  {
    key: 'renan-araujo',
    name: 'Renan Araujo',
    phone: '(11) 99123-1104',
    email: 'renan.araujo@email.com',
    type: CustomerType.SUBSCRIPTION,
    subscriptionPrice: 219.9,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    preferredProfessionalKey: 'lucas-ribeiro',
  },
  {
    key: 'marcos-leite',
    name: 'Marcos Leite',
    phone: '(11) 99123-1111',
    email: 'marcos.leite@email.com',
    type: CustomerType.SUBSCRIPTION,
    subscriptionPrice: 199.9,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    preferredProfessionalKey: 'lucas-ribeiro',
    notes: 'Assinante com uso mais baixo, bom para leitura de saude da base.',
  },
  {
    key: 'eduardo-lima',
    name: 'Eduardo Lima',
    phone: '(11) 99123-1113',
    email: 'eduardo.lima@email.com',
    type: CustomerType.SUBSCRIPTION,
    subscriptionPrice: 189.9,
    subscriptionStatus: SubscriptionStatus.ACTIVE,
    preferredProfessionalKey: 'rafael-costa',
  },
  {
    key: 'felipe-duarte',
    name: 'Felipe Duarte',
    phone: '(11) 99123-1105',
    email: 'felipe.duarte@email.com',
    type: CustomerType.WALK_IN,
    preferredProfessionalKey: 'matheus-lima',
  },
  {
    key: 'guilherme-prado',
    name: 'Guilherme Prado',
    phone: '(11) 99123-1106',
    email: 'guilherme.prado@email.com',
    type: CustomerType.WALK_IN,
    preferredProfessionalKey: 'matheus-lima',
  },
  {
    key: 'vinicius-amaral',
    name: 'Vinicius Amaral',
    phone: '(11) 99123-1107',
    email: 'vinicius.amaral@email.com',
    type: CustomerType.WALK_IN,
    preferredProfessionalKey: 'lucas-ribeiro',
  },
  {
    key: 'rafael-nunes',
    name: 'Rafael Nunes',
    phone: '(11) 99123-1108',
    email: 'rafael.nunes@email.com',
    type: CustomerType.WALK_IN,
    preferredProfessionalKey: 'lucas-ribeiro',
  },
  {
    key: 'joao-victor',
    name: 'Joao Victor',
    phone: '(11) 99123-1109',
    email: 'joao.victor@email.com',
    type: CustomerType.WALK_IN,
    preferredProfessionalKey: 'matheus-lima',
  },
  {
    key: 'douglas-freitas',
    name: 'Douglas Freitas',
    phone: '(11) 99123-1110',
    email: 'douglas.freitas@email.com',
    type: CustomerType.WALK_IN,
    preferredProfessionalKey: 'matheus-lima',
  },
  {
    key: 'rodrigo-sena',
    name: 'Rodrigo Sena',
    phone: '(11) 99123-1112',
    email: 'rodrigo.sena@email.com',
    type: CustomerType.WALK_IN,
    preferredProfessionalKey: 'lucas-ribeiro',
  },
  {
    key: 'andre-luiz',
    name: 'Andre Luiz',
    phone: '(11) 99123-1114',
    email: 'andre.luiz@email.com',
    type: CustomerType.WALK_IN,
    preferredProfessionalKey: 'matheus-lima',
  },
]

export const SUBSCRIPTION_CUSTOMER_POOL = [
  'carlos-mendes',
  'pedro-salles',
  'pedro-salles',
  'thiago-rocha',
  'renan-araujo',
  'renan-araujo',
  'marcos-leite',
  'eduardo-lima',
]

export const WALK_IN_CUSTOMER_POOL = [
  'felipe-duarte',
  'guilherme-prado',
  'vinicius-amaral',
  'rafael-nunes',
  'joao-victor',
  'douglas-freitas',
  'rodrigo-sena',
  'andre-luiz',
  'andre-luiz',
]

export const PAYMENT_METHODS = [
  PaymentMethod.PIX,
  PaymentMethod.CREDIT_CARD,
  PaymentMethod.DEBIT_CARD,
  PaymentMethod.CASH,
]

export const SERVICE_VARIATIONS = [-3, 0, 2, 4]

export const TODAY_AND_FUTURE_SCHEDULE: ScheduleBlueprint[] = [
  {
    key: 'today-lucas-carlos',
    dayOffset: 0,
    time: '09:00',
    professionalKey: 'lucas-ribeiro',
    customerKey: 'carlos-mendes',
    serviceKey: 'corte-classic',
    status: AppointmentStatus.COMPLETED,
    source: AppointmentSource.MANUAL,
  },
  {
    key: 'today-rafael-pedro',
    dayOffset: 0,
    time: '10:30',
    professionalKey: 'rafael-costa',
    customerKey: 'pedro-salles',
    serviceKey: 'corte-barba-premium',
    status: AppointmentStatus.COMPLETED,
    source: AppointmentSource.WHATSAPP,
    billingModel: AppointmentBillingModel.SUBSCRIPTION_EXTRA,
    notes: 'Cliente confirmou pelo WhatsApp e veio para o combo premium.',
  },
  {
    key: 'today-matheus-felipe',
    dayOffset: 0,
    time: '11:00',
    professionalKey: 'matheus-lima',
    customerKey: 'felipe-duarte',
    serviceKey: 'degrade-signature',
    status: AppointmentStatus.COMPLETED,
    source: AppointmentSource.MANUAL,
  },
  {
    key: 'today-lucas-renan',
    dayOffset: 0,
    time: '14:00',
    professionalKey: 'lucas-ribeiro',
    customerKey: 'renan-araujo',
    serviceKey: 'degrade-signature',
    status: AppointmentStatus.CONFIRMED,
    source: AppointmentSource.WHATSAPP,
  },
  {
    key: 'today-rafael-thiago',
    dayOffset: 0,
    time: '15:00',
    professionalKey: 'rafael-costa',
    customerKey: 'thiago-rocha',
    serviceKey: 'hidratacao-capilar',
    status: AppointmentStatus.PENDING,
    source: AppointmentSource.WHATSAPP,
    billingModel: AppointmentBillingModel.SUBSCRIPTION_EXTRA,
  },
  {
    key: 'today-matheus-guilherme',
    dayOffset: 0,
    time: '16:30',
    professionalKey: 'matheus-lima',
    customerKey: 'guilherme-prado',
    serviceKey: 'barba-terapia',
    status: AppointmentStatus.CONFIRMED,
    source: AppointmentSource.MANUAL,
  },
  {
    key: 'tomorrow-lucas-marcos',
    dayOffset: 1,
    time: '09:30',
    professionalKey: 'lucas-ribeiro',
    customerKey: 'marcos-leite',
    serviceKey: 'corte-classic',
    status: AppointmentStatus.CONFIRMED,
    source: AppointmentSource.MANUAL,
  },
  {
    key: 'tomorrow-matheus-joao',
    dayOffset: 1,
    time: '11:30',
    professionalKey: 'matheus-lima',
    customerKey: 'joao-victor',
    serviceKey: 'corte-classic',
    status: AppointmentStatus.CONFIRMED,
    source: AppointmentSource.WHATSAPP,
  },
  {
    key: 'tomorrow-rafael-eduardo',
    dayOffset: 1,
    time: '14:30',
    professionalKey: 'rafael-costa',
    customerKey: 'eduardo-lima',
    serviceKey: 'barba-terapia',
    status: AppointmentStatus.CANCELLED,
    source: AppointmentSource.WHATSAPP,
  },
  {
    key: 'plus2-lucas-vinicius',
    dayOffset: 2,
    time: '10:00',
    professionalKey: 'lucas-ribeiro',
    customerKey: 'vinicius-amaral',
    serviceKey: 'corte-barba-premium',
    status: AppointmentStatus.CONFIRMED,
    source: AppointmentSource.MANUAL,
  },
  {
    key: 'plus2-matheus-douglas',
    dayOffset: 2,
    time: '17:00',
    professionalKey: 'matheus-lima',
    customerKey: 'douglas-freitas',
    serviceKey: 'hidratacao-capilar',
    status: AppointmentStatus.PENDING,
    source: AppointmentSource.WHATSAPP,
  },
]

export const FIXED_EXPENSE_TEMPLATES: SeedExpenseTemplate[] = [
  {
    description: 'Aluguel da unidade',
    amount: 4200,
    categoryKey: 'aluguel',
    dueDay: 5,
    paid: true,
    recurrent: true,
  },
  {
    description: 'Pro-labore da operacao',
    amount: 1800,
    categoryKey: 'folha',
    dueDay: 6,
    paid: true,
    recurrent: true,
  },
  {
    description: 'Energia e agua',
    amount: 640,
    categoryKey: 'utilidades',
    dueDay: 10,
    paid: false,
    recurrent: true,
  },
  {
    description: 'Internet, agenda e software',
    amount: 289,
    categoryKey: 'software',
    dueDay: 8,
    paid: false,
    recurrent: true,
  },
]

export const VARIABLE_EXPENSE_TEMPLATES: SeedExpenseTemplate[] = [
  {
    description: 'Reposicao de insumos premium',
    amount: 760,
    categoryKey: 'insumos',
    dueDay: 14,
    paid: false,
    recurrent: false,
  },
  {
    description: 'Campanha local de Instagram',
    amount: 420,
    categoryKey: 'marketing',
    dueDay: 12,
    paid: false,
    recurrent: false,
  },
  {
    description: 'Manutencao preventiva das maquinas',
    amount: 240,
    categoryKey: 'manutencao',
    dueDay: 18,
    paid: false,
    recurrent: false,
  },
]

export const CAMPAIGN_METRIC_DEFINITIONS: SeedCampaignMetricDefinition[] = [
  {
    key: 'reactivation',
    monthOffset: 1,
    campaignName: 'Reativacao de clientes parados',
    messagesSent: 164,
    messagesAnswered: 63,
    appointmentsBooked: 38,
    newClients: 11,
    recoveredClients: 27,
    notes: 'Campanha que ajudou a encher agenda nas segundas e tercas.',
  },
  {
    key: 'premium-combo',
    monthOffset: 0,
    campaignName: 'Combo premium de inicio de mes',
    messagesSent: 118,
    messagesAnswered: 49,
    appointmentsBooked: 29,
    newClients: 9,
    recoveredClients: 16,
    notes: 'Campanha voltada para ticket medio e recompra.',
  },
]
